config/routes.rb
Rails.application.routes.draw do
  resources :fyber_offers, only: :index do
    collection do
      get 'search'
    end
  end

  root 'fyber_offers#index'
end

app/models/fyber_request.rb
class FyberRequest
  require 'digest/sha1'
  include HTTParty
  
  attr_reader :appid, :pub0, :page, :uid, :device_id, :locale, :ip, 
    :offer_types, :ps_time, :timestamp, :os_version, :message

  base_uri 'api.sponsorpay.com/feed/v1'
  
  def initialize(args)
    @uid = args[:uid]
    @pub0 = args[:pub0]
    @page = args[:page]
    @ps_time = args[:ps_time]
    @os_version = args[:os_version]
    @device_id = args[:device_id] || '2b6f0cc904d137be2e1730235f5664094b831186'
    @locale = args[:locale] || 'de'
    @ip = args[:ip] || '109.235.143.113'
    @offer_types = args[:offer_types]
    @appid = args[:appid] || '157'
    @timestamp = args[:timestamp] || Time.now.to_i
  end
  
  def get_offers
    response = self.class.get('/offers.json', options)
    @message = response.parsed_response['message']
    if response_signature(response.body) == response.headers['x-sponsorpay-response-signature']
      return response.parsed_response[:offers]
    else
      @message = "Tampered response. Invalid Signature" if response.headers['x-sponsorpay-response-signature'].present?
      return nil
    end
  end
    
  def options
    {query: request_parameters.merge({hashkey: hashkey})}
  end
    
  def request_parameters
    params = {uid: @uid, appid: @appid, device_id: @device_id, locale: @locale,  timestamp: @timestamp}
    params[:offer_types] = @offer_types if @offer_types.present?
    params[:ip] = @ip if @ip.present?
    params[:os_version] = @os_version if @os_version.present?
    params[:pub0] = @pub0 if @pub0.present?
    params[:page] = @page if @page.present?
    params[:ps_time] = @ps_time if @ps_time.present?
    params
  end
    
  def hashkey
    request_params = request_parameters.keys.sort.map{|key| "#{key}=#{request_parameters[key]}"}.join('&')
    Digest::SHA1.hexdigest "#{request_params}&#{Rails.application.secrets.fyber_api_key}"
  end
  
  def response_signature(body)
    Digest::SHA1.hexdigest "#{body}#{Rails.application.secrets.fyber_api_key}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fyber_offers_controller.rb
class FyberOffersController < ApplicationController
  # GET /fyber_offers
  def index
  end
  
  # GET/fyber_offers/search
  def search
    @request = FyberRequest.new(fyber_offer_params)
    @offers = @request.get_offers
    flash[:alert] = @request.message unless @offers.present?
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def fyber_offer_params
      params.require(:fyber_offer).permit(:uid, :pub0, :page)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fyber_offers/_no_offers.html.erb
<div class='no_offers'>
  No offers
</div>

app/views/fyber_offers/_offer.html.erb
<div class='row offer'>
  <div class='title'><%= offer[:title] %></div>
  <div class='payout'><%= offer[:payout] %></div>
  <div class='thumbnail'><%= image_tag offer[:thumbnail][:lowres] %></div>
</div>

app/views/fyber_offers/_search_form.html.erb
<%= form_for :fyber_offer, url: search_fyber_offers_path, method: :get, html: {class: "form-horizontal", role: "form"} do |f| %>
  <div class="form-group form-group-sm">
    <%= f.label :uid, "UID", class: "col-sm-1 control-label" %>
    <div class="col-sm-3">
      <%= f.text_field :uid, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group form-group-sm">
    <%= f.label :pub0, "Pub0", class: "col-sm-1 control-label" %>
    <div class="col-sm-3">
      <%= f.text_field :pub0, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group form-group-sm">
    <%= f.label :page, "Page", class: "col-sm-1 control-label" %>
    <div class="col-sm-3">
      <%= f.text_field :page, type: :number, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group form-group-sm">
    <div class="col-sm-offset-1 col-sm-10">
      <button type="submit" class="btn btn-default">Submit</button>
    </div>
  </div>
<% end %>

app/views/fyber_offers/index.html.erb
<h1>Fyber Offers</h1>

<div class="row">
  <%= render partial: "search_form" %>
</div>

app/views/fyber_offers/search.html.erb
<h1>Fyber Offers</h1>

<div class="row">
  <%= render partial: "search_form" %>
</div>

<div id='row results'>
  <h2>Results</h2>
  <% if @offers.blank? %>
    <%= render partial: 'no_offers' %>
  <% else %>
    <%= render partial: 'offer', collection: @offers %>
  <% end %>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FyberChallenge" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">FyberChallenge</a>
        
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

  </body>
</html>